<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:dirwsdl="http://www.wscomposition.org/Directions/" xmlns:forwsdl="http://www.wscomposition.org/Forecast/" xmlns:plawsdl="http://www.wscomposition.org/Places/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://composer" xmlns:types="http://ode/bpel/types" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:youwsdl="http://www.wscomposition.org/Youtube/" name="Composer" targetNamespace="http://composer">
   <documentation>Web service (orchestrator) of the other WS</documentation>
   <plnk:partnerLinkType name="DirectionsPLT">
      <plnk:role name="DirectionsRole" portType="dirwsdl:Directions" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="PlacesPLT">
      <plnk:role name="PlacesRole" portType="plawsdl:Places" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="YoutubePLT">
      <plnk:role name="YoutubeRole" portType="youwsdl:Youtube" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="ForecastPLT">
      <plnk:role name="ForecastRole" portType="forwsdl:Forecast" />
   </plnk:partnerLinkType>
   <import location="Directions.wsdl" namespace="http://www.wscomposition.org/Directions/" />
   <import location="Places.wsdl" namespace="http://www.wscomposition.org/Places/" />
   <import location="Youtube.wsdl" namespace="http://www.wscomposition.org/Youtube/" />
   <import location="Forecast.wsdl" namespace="http://www.wscomposition.org/Forecast/" />
   <message name="ComposerRequestMessage">
      <part name="origin" type="xsd:string" />
      <part name="destination" type="xsd:string" />
      <part name="radius" type="xsd:integer" />
      <part name="types" type="xsd:string" />
      <part name="key" type="xsd:string" />
      <part name="sensor" type="xsd:string" />
      <part name="mode" type="xsd:string" />
   </message>
   <message name="ComposerResponseMessage">
      <part name="response" type="xsd:string" />
   </message>
   <portType name="Composer">
      <operation name="process">
         <input message="tns:ComposerRequestMessage" />
         <output message="tns:ComposerResponseMessage" />
      </operation>
   </portType>
   <plnk:partnerLinkType name="Composer">
      <plnk:role name="ComposerProvider" portType="tns:Composer" />
   </plnk:partnerLinkType>
   <!-- maybe switch to document literal -->
   <binding name="ComposerBinding" type="tns:Composer">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
      <operation name="process">
         <soap:operation soapAction="http://composer/process" />
         <input>
            <soap:body use="literal" namespace="http://composer" />
         </input>
         <output>
            <soap:body use="literal" namespace="http://composer" />
         </output>
      </operation>
   </binding>
   <service name="ComposerService">
      <port binding="tns:ComposerBinding" name="ComposerPort">
         <soap:address location="http://localhost:8080/ode/processes/Composer" />
      </port>
   </service>
</definitions>