<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://www.wscomposition.org/Search/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Search" targetNamespace="http://www.wscomposition.org/Search/">
   <wsdl:documentation>WSDL 1.1 Interface for Google Custom Search web service</wsdl:documentation>
   <wsdl:message name="Request">
      <wsdl:part name="q" type="xsd:string" />
      <wsdl:part name="key" type="xsd:string" />
      <wsdl:part name="cx" type="xsd:string" />
      <wsdl:part name="alt" type="xsd:string" />
      <wsdl:part name="searchType" type="xsd:string" />
      <wsdl:part name="num" type="xsd:integer" />
   </wsdl:message>
   <wsdl:message name="Response">
      <wsdl:part name="SearchResponse" type="xsd:string" />
   </wsdl:message>
   <wsdl:portType name="Search">
      <wsdl:documentation>Interface for the single operation, v1</wsdl:documentation>
      <wsdl:operation name="v1">
         <wsdl:input message="tns:Request" name="simpleRequest" />
         <wsdl:output message="tns:Response" name="simpleResponse" />
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="SearchHTTP" type="tns:Search">
      <http:binding verb="GET" />
      <wsdl:operation name="v1">
         <http:operation location="v1" />
         <wsdl:input name="simpleRequest">
            <http:urlEncoded />
         </wsdl:input>
         <wsdl:output name="simpleResponse">
            <mime:content type="text/xml" part="SearchResponse" />
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Search">
      <wsdl:port binding="tns:SearchHTTP" name="SearchHTTP">
         <http:address location="https://www.googleapis.com/customsearch" />
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>