<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:dirwsdl="http://www.wscomposition.org/Directions/" xmlns:forwsdl="http://www.wscomposition.org/Forecast/" xmlns:plawsdl="http://www.wscomposition.org/Places/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://travel" xmlns:types="http://ode/bpel/types" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:seawsdl="http://www.wscomposition.org/Search/" name="Travel" targetNamespace="http://travel">
   <documentation>Travel web service</documentation>
   <plnk:partnerLinkType name="DirectionsPLT">
      <plnk:role name="DirectionsRole" portType="dirwsdl:Directions" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="PlacesPLT">
      <plnk:role name="PlacesRole" portType="plawsdl:Places" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="ForecastPLT">
      <plnk:role name="ForecastRole" portType="forwsdl:Forecast" />
   </plnk:partnerLinkType>
   <plnk:partnerLinkType name="SearchPLT">
      <plnk:role name="SearchRole" portType="seawsdl:Search" />
   </plnk:partnerLinkType>
   <import location="Directions.wsdl" namespace="http://www.wscomposition.org/Directions/" />
   <import location="Places.wsdl" namespace="http://www.wscomposition.org/Places/" />
   <import location="Forecast.wsdl" namespace="http://www.wscomposition.org/Forecast/" />
   <import location="Search.wsdl" namespace="http://www.wscomposition.org/Search/" />
   <message name="TravelRequestMessage">
      <part name="origin" type="xsd:string" />
      <part name="destination" type="xsd:string" />
      <part name="travelMode" type="xsd:string" />
      <part name="objectiveRadius" type="xsd:integer" />
      <part name="objectiveTypes" type="xsd:string" />
      <part name="forecastUnits" type="xsd:string" />
      <part name="forecastDays" type="xsd:integer" />
      <part name="images" type="xsd:integer" />
   </message>
   <message name="TravelResponseMessage">
      <part name="TravelResponse" type="xsd:string" />
   </message>
   <portType name="Travel">
      <operation name="getInfo">
         <input message="tns:TravelRequestMessage" />
         <output message="tns:TravelResponseMessage" />
      </operation>
   </portType>
   <plnk:partnerLinkType name="Travel">
      <plnk:role name="TravelProvider" portType="tns:Travel" />
   </plnk:partnerLinkType>
   <!-- maybe switch to document literal -->
   <binding name="TravelBinding" type="tns:Travel">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
      <operation name="getInfo">
         <soap:operation soapAction="http://travel/getInfo" />
         <input>
            <soap:body use="literal" namespace="http://travel" />
         </input>
         <output>
            <soap:body use="literal" namespace="http://travel" />
         </output>
      </operation>
   </binding>
   <service name="TravelService">
      <port binding="tns:TravelBinding" name="TravelPort">
         <soap:address location="http://localhost:8080/ode/processes/Travel" />
      </port>
   </service>
</definitions>