<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://www.wscomposition.org/Directions/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Directions" targetNamespace="http://www.wscomposition.org/Directions/">
   <wsdl:documentation>WSDL for Google Directions web service</wsdl:documentation>
   <wsdl:message name="Request">
      <wsdl:part name="origin" type="xsd:string" />
      <wsdl:part name="destination" type="xsd:string" />
      <wsdl:part name="sensor" type="xsd:string" />
   </wsdl:message>
   <wsdl:message name="Response">
      <wsdl:part name="dir_response" type="xsd:string" />
   </wsdl:message>
   <wsdl:portType name="Directions">
      <wsdl:documentation>Interface for the 2 operations: xml and json</wsdl:documentation>
      <wsdl:operation name="xml">
         <wsdl:input message="tns:Request" name="xmlRequest" />
         <wsdl:output message="tns:Response" name="xmlResponse" />
      </wsdl:operation>
      <wsdl:operation name="json">
         <wsdl:input message="tns:Request" name="jsonRequest" />
         <wsdl:output message="tns:Response" name="jsonResponse" />
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="DirectionsHTTP" type="tns:Directions">
      <http:binding verb="GET" />
      <wsdl:operation name="xml">
         <http:operation location="xml" />
         <wsdl:input name="xmlRequest">
            <http:urlEncoded />
            <!-- or replacement -->
         </wsdl:input>
         <wsdl:output name="xmlResponse">
            <mime:content type="text/xml" part="dir_response" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="json">
         <http:operation location="json" />
         <wsdl:input name="jsonRequest">
            <http:urlEncoded />
         </wsdl:input>
         <wsdl:output name="jsonResponse">
            <!-- if this part is missing, the call will fail -->
            <mime:content type="application/json" part="dir_response" />
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="Directions">
      <wsdl:port binding="tns:DirectionsHTTP" name="DirectionsHTTP">
         <http:address location="http://maps.googleapis.com/maps/api/directions" />
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>